name: CI

on:
  pull_request:
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: checkout tiddlywiki
      if: github.event.pull_request.merged == true
      run: git clone https://github.com/Jermolene/TiddlyWiki5 tiddlywiki
    - name: prepare environment
      if: github.event.pull_request.merged == true
      run: |
          git config user.email "iilyak@apache.org"
          git config user.name "$GITHUB_ACTOR"
    - name: build demo
      if: github.event.pull_request.merged == true
      run: TIDDLYWIKI_PATH=`pwd`/tiddlywiki make build
    - name: deploy demo
      if: github.event.pull_request.merged == true
      run: |
          make deploy
          cd site
          git push origin gh-pages
